/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import tubespbo_autogatesystem.database;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDateTime; 
import java.time.format.DateTimeFormatter; 
import java.text.SimpleDateFormat;  
import javax.swing.JOptionPane;


/**
 *
 * @author maula
 */
public class DataScientist_Dashboard_Home extends javax.swing.JFrame {

    /**
     * Creates new form Security_Dashboard_Home
     */
    public DataScientist_Dashboard_Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        panel_logout = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        panel_bydate3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        panel_bydate4 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        panel_bydate5 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        panel_bydate6 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        panel_bydate7 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        TabbedPane_Dashboard = new javax.swing.JTabbedPane();
        panel_getAllPeople = new javax.swing.JPanel();
        tabel_data2 = new javax.swing.JScrollPane();
        tabel_getalldata = new javax.swing.JTable();
        kGradientPanel5 = new keeptoo.KGradientPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        kGradientPanel6 = new keeptoo.KGradientPanel();
        jLabel19 = new javax.swing.JLabel();
        panel_getdatapeoplebydate = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_getAllDataByDate = new javax.swing.JTable();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel7 = new javax.swing.JLabel();
        kGradientPanel7 = new keeptoo.KGradientPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        datechooser_getpeople = new com.toedter.calendar.JDateChooser();
        panel_getdatapeoplebymonth = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_databydate = new javax.swing.JTable();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        jLabel15 = new javax.swing.JLabel();
        get_year = new com.toedter.calendar.JYearChooser();
        get_month = new com.toedter.calendar.JMonthChooser();
        panel_getjumlahvisitorbydate = new javax.swing.JPanel();
        kGradientPanel8 = new keeptoo.KGradientPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        kGradientPanel9 = new keeptoo.KGradientPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        datechooser_jumlahpeople = new com.toedter.calendar.JDateChooser();
        kGradientPanel12 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jumlah = new javax.swing.JLabel();
        panel_getjumlahvisitorbymonth = new javax.swing.JPanel();
        kGradientPanel10 = new keeptoo.KGradientPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        kGradientPanel11 = new keeptoo.KGradientPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        get_jumlahmonth = new com.toedter.calendar.JMonthChooser();
        get_jumlahyear = new com.toedter.calendar.JYearChooser();
        kGradientPanel13 = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jumlah1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 255, 255));
        kGradientPanel1.setkGradientFocus(300);
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 102, 204));

        panel_logout.setOpaque(false);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/logout.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("LOG OUT");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14homepage(evt);
            }
        });

        javax.swing.GroupLayout panel_logoutLayout = new javax.swing.GroupLayout(panel_logout);
        panel_logout.setLayout(panel_logoutLayout);
        panel_logoutLayout.setHorizontalGroup(
            panel_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_logoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_logoutLayout.setVerticalGroup(
            panel_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_logoutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panel_bydate3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_bydate3.setOpaque(false);
        panel_bydate3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_bydate3MouseClicked(evt);
            }
        });

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/calendar.png"))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("ALL PEOPLE");
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24homepage(evt);
            }
        });

        javax.swing.GroupLayout panel_bydate3Layout = new javax.swing.GroupLayout(panel_bydate3);
        panel_bydate3.setLayout(panel_bydate3Layout);
        panel_bydate3Layout.setHorizontalGroup(
            panel_bydate3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bydate3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panel_bydate3Layout.setVerticalGroup(
            panel_bydate3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bydate3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_bydate3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_bydate4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_bydate4.setOpaque(false);
        panel_bydate4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_bydate4MouseClicked(evt);
            }
        });

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/calendar.png"))); // NOI18N

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("BY DATE");
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26homepage(evt);
            }
        });

        javax.swing.GroupLayout panel_bydate4Layout = new javax.swing.GroupLayout(panel_bydate4);
        panel_bydate4.setLayout(panel_bydate4Layout);
        panel_bydate4Layout.setHorizontalGroup(
            panel_bydate4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bydate4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel26)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        panel_bydate4Layout.setVerticalGroup(
            panel_bydate4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bydate4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_bydate4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel25))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panel_bydate5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_bydate5.setOpaque(false);
        panel_bydate5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_bydate5MouseClicked(evt);
            }
        });

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/calendar.png"))); // NOI18N

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("BY MONTH");
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28homepage(evt);
            }
        });

        javax.swing.GroupLayout panel_bydate5Layout = new javax.swing.GroupLayout(panel_bydate5);
        panel_bydate5.setLayout(panel_bydate5Layout);
        panel_bydate5Layout.setHorizontalGroup(
            panel_bydate5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bydate5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel28)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        panel_bydate5Layout.setVerticalGroup(
            panel_bydate5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bydate5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_bydate5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel27))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_bydate6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_bydate6.setOpaque(false);
        panel_bydate6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_bydate6MouseClicked(evt);
            }
        });

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/calendar.png"))); // NOI18N

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("BY DATE");
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30homepage(evt);
            }
        });

        javax.swing.GroupLayout panel_bydate6Layout = new javax.swing.GroupLayout(panel_bydate6);
        panel_bydate6.setLayout(panel_bydate6Layout);
        panel_bydate6Layout.setHorizontalGroup(
            panel_bydate6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bydate6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel30)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        panel_bydate6Layout.setVerticalGroup(
            panel_bydate6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bydate6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_bydate6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel29))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_bydate7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_bydate7.setOpaque(false);
        panel_bydate7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_bydate7MouseClicked(evt);
            }
        });

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/calendar.png"))); // NOI18N

        jLabel32.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("BY MONTH");
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32homepage(evt);
            }
        });

        javax.swing.GroupLayout panel_bydate7Layout = new javax.swing.GroupLayout(panel_bydate7);
        panel_bydate7.setLayout(panel_bydate7Layout);
        panel_bydate7Layout.setHorizontalGroup(
            panel_bydate7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bydate7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel32)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_bydate7Layout.setVerticalGroup(
            panel_bydate7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bydate7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_bydate7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(jLabel31))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_bydate4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_bydate5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_bydate6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_bydate7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_bydate3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(panel_bydate3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_bydate4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_bydate5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_bydate6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_bydate7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(panel_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 440));

        TabbedPane_Dashboard.setBackground(new java.awt.Color(255, 255, 255));

        panel_getAllPeople.setBackground(new java.awt.Color(255, 255, 255));
        panel_getAllPeople.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel_getalldata.setBackground(new java.awt.Color(255, 204, 255));
        tabel_getalldata.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabel_getalldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "dataharian_id", "namadepan", "namabelakang", "email", "input_at"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_data2.setViewportView(tabel_getalldata);

        panel_getAllPeople.add(tabel_data2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 620, 310));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("GENERATE");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.setVerifyInputWhenFocusTarget(false);
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel5Layout = new javax.swing.GroupLayout(kGradientPanel5);
        kGradientPanel5.setLayout(kGradientPanel5Layout);
        kGradientPanel5Layout.setHorizontalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        kGradientPanel5Layout.setVerticalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panel_getAllPeople.add(kGradientPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 120, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("MENU GET ALL PEOPLE");
        panel_getAllPeople.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 290, 35));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("CLEAR");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.setVerifyInputWhenFocusTarget(false);
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel6Layout = new javax.swing.GroupLayout(kGradientPanel6);
        kGradientPanel6.setLayout(kGradientPanel6Layout);
        kGradientPanel6Layout.setHorizontalGroup(
            kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel6Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel19)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        kGradientPanel6Layout.setVerticalGroup(
            kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panel_getAllPeople.add(kGradientPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        TabbedPane_Dashboard.addTab("tab3", panel_getAllPeople);

        panel_getdatapeoplebydate.setBackground(new java.awt.Color(255, 255, 255));
        panel_getdatapeoplebydate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("MENU GET PEOPLE DATA BY DATE");
        panel_getdatapeoplebydate.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 310, 35));

        tabel_getAllDataByDate.setBackground(new java.awt.Color(255, 204, 255));
        tabel_getAllDataByDate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabel_getAllDataByDate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "dataharian_id", "namadepan", "namabelakang", "email", "input_at"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabel_getAllDataByDate);

        panel_getdatapeoplebydate.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 620, 310));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("GENERATE");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.setVerifyInputWhenFocusTarget(false);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panel_getdatapeoplebydate.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 120, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("CLEAR");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.setVerifyInputWhenFocusTarget(false);
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel7Layout = new javax.swing.GroupLayout(kGradientPanel7);
        kGradientPanel7.setLayout(kGradientPanel7Layout);
        kGradientPanel7Layout.setHorizontalGroup(
            kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel7Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel20)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        kGradientPanel7Layout.setVerticalGroup(
            kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panel_getdatapeoplebydate.add(kGradientPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("choose date ");
        panel_getdatapeoplebydate.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 35));

        datechooser_getpeople.setOpaque(false);
        panel_getdatapeoplebydate.add(datechooser_getpeople, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 190, -1));

        TabbedPane_Dashboard.addTab("tab1", panel_getdatapeoplebydate);

        panel_getdatapeoplebymonth.setBackground(new java.awt.Color(255, 255, 255));
        panel_getdatapeoplebymonth.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("choose date ");
        panel_getdatapeoplebymonth.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 35));

        tabel_databydate.setBackground(new java.awt.Color(255, 204, 255));
        tabel_databydate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabel_databydate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "dataharian_id", "namadepan", "namabelakang", "email", "input_at"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabel_databydate);

        panel_getdatapeoplebymonth.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 620, 310));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("GENERATE");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.setVerifyInputWhenFocusTarget(false);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panel_getdatapeoplebymonth.add(kGradientPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 120, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("MENU GET ALL DATA PEOPLE BY MONTH");
        panel_getdatapeoplebymonth.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 380, 35));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("CLEAR");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.setVerifyInputWhenFocusTarget(false);
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel15)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panel_getdatapeoplebymonth.add(kGradientPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));
        panel_getdatapeoplebymonth.add(get_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));
        panel_getdatapeoplebymonth.add(get_month, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        TabbedPane_Dashboard.addTab("tab2", panel_getdatapeoplebymonth);

        panel_getjumlahvisitorbydate.setBackground(new java.awt.Color(255, 255, 255));
        panel_getjumlahvisitorbydate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("GENERATE");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.setVerifyInputWhenFocusTarget(false);
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel8Layout = new javax.swing.GroupLayout(kGradientPanel8);
        kGradientPanel8.setLayout(kGradientPanel8Layout);
        kGradientPanel8Layout.setHorizontalGroup(
            kGradientPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        kGradientPanel8Layout.setVerticalGroup(
            kGradientPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panel_getjumlahvisitorbydate.add(kGradientPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 120, 30));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("MENU GET JUMLAH VISITOR BY DATE");
        panel_getjumlahvisitorbydate.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 330, 35));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("CLEAR");
        jLabel33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel33.setVerifyInputWhenFocusTarget(false);
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel9Layout = new javax.swing.GroupLayout(kGradientPanel9);
        kGradientPanel9.setLayout(kGradientPanel9Layout);
        kGradientPanel9Layout.setHorizontalGroup(
            kGradientPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel9Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel33)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        kGradientPanel9Layout.setVerticalGroup(
            kGradientPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panel_getjumlahvisitorbydate.add(kGradientPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("choose date ");
        panel_getjumlahvisitorbydate.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 35));

        datechooser_jumlahpeople.setOpaque(false);
        panel_getjumlahvisitorbydate.add(datechooser_jumlahpeople, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 190, -1));

        kGradientPanel12.setkEndColor(new java.awt.Color(255, 255, 51));
        kGradientPanel12.setkStartColor(new java.awt.Color(0, 255, 204));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("JUMLAH DATA SEBANYAK");

        jumlah.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jumlah.setText("25");

        javax.swing.GroupLayout kGradientPanel12Layout = new javax.swing.GroupLayout(kGradientPanel12);
        kGradientPanel12.setLayout(kGradientPanel12Layout);
        kGradientPanel12Layout.setHorizontalGroup(
            kGradientPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel12Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jumlah)
                .addGap(128, 128, 128))
        );
        kGradientPanel12Layout.setVerticalGroup(
            kGradientPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jumlah)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        panel_getjumlahvisitorbydate.add(kGradientPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 300, 110));

        TabbedPane_Dashboard.addTab("tab3", panel_getjumlahvisitorbydate);

        panel_getjumlahvisitorbymonth.setBackground(new java.awt.Color(255, 255, 255));
        panel_getjumlahvisitorbymonth.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("GENERATE");
        jLabel34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel34.setVerifyInputWhenFocusTarget(false);
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel10Layout = new javax.swing.GroupLayout(kGradientPanel10);
        kGradientPanel10.setLayout(kGradientPanel10Layout);
        kGradientPanel10Layout.setHorizontalGroup(
            kGradientPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel10Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        kGradientPanel10Layout.setVerticalGroup(
            kGradientPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panel_getjumlahvisitorbymonth.add(kGradientPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 120, 30));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel35.setText("MENU GET ALL JUMLAH BY MONTH");
        panel_getjumlahvisitorbymonth.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 320, 35));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("CLEAR");
        jLabel36.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel36.setVerifyInputWhenFocusTarget(false);
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel11Layout = new javax.swing.GroupLayout(kGradientPanel11);
        kGradientPanel11.setLayout(kGradientPanel11Layout);
        kGradientPanel11Layout.setHorizontalGroup(
            kGradientPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel11Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel36)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        kGradientPanel11Layout.setVerticalGroup(
            kGradientPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panel_getjumlahvisitorbymonth.add(kGradientPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("choose date ");
        panel_getjumlahvisitorbymonth.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 35));
        panel_getjumlahvisitorbymonth.add(get_jumlahmonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));
        panel_getjumlahvisitorbymonth.add(get_jumlahyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        kGradientPanel13.setkEndColor(new java.awt.Color(255, 255, 51));
        kGradientPanel13.setkStartColor(new java.awt.Color(0, 255, 204));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("JUMLAH DATA SEBANYAK");

        jumlah1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jumlah1.setText("25");

        javax.swing.GroupLayout kGradientPanel13Layout = new javax.swing.GroupLayout(kGradientPanel13);
        kGradientPanel13.setLayout(kGradientPanel13Layout);
        kGradientPanel13Layout.setHorizontalGroup(
            kGradientPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel13Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jumlah1)
                .addGap(128, 128, 128))
        );
        kGradientPanel13Layout.setVerticalGroup(
            kGradientPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jumlah1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        panel_getjumlahvisitorbymonth.add(kGradientPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 300, 110));

        TabbedPane_Dashboard.addTab("tab3", panel_getjumlahvisitorbymonth);

        getContentPane().add(TabbedPane_Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, -50, 660, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel14homepage(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14homepage
        // TODO add your handling code here:
        String[] options = {"NO", "YES" };
        int x = JOptionPane.showOptionDialog(null, "Apakah anda yakin untuk keluar?", "Verifikasi Masker", JOptionPane.DEFAULT_OPTION,JOptionPane.WARNING_MESSAGE, null, options, options[0]);
        if ( x == 1){
            Login loginpage = new Login();
            loginpage.show();
            dispose();
        }    
    }//GEN-LAST:event_jLabel14homepage

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = sdf.format(datechooser_getpeople.getDate());
        try {
            String querry_data = String.format("SELECT dataharian.dataharian_id, user.nama_depan, user.nama_belakang, user.email, dataharian.input_at FROM user INNER JOIN dataharian ON user.user_id = dataharian.user_id WHERE input_at = '%s'", tanggal);
            Connection conn = database.getConnect();
            PreparedStatement get_data = conn.prepareStatement(querry_data);
            ResultSet hasil = get_data.executeQuery();
		            
            while(hasil.next()) {
                String dataharian_id = String.valueOf(hasil.getInt("dataharian_id"));
                String namadepan = hasil.getString("nama_depan");
                String namabelakang = hasil.getString("nama_belakang");
                String email = hasil.getString("email");
                String input_at = hasil.getString("input_at");
		            	
                String tbData[] = {dataharian_id, namadepan, namabelakang, email, input_at};
                DefaultTableModel tblModel = (DefaultTableModel)tabel_getAllDataByDate.getModel();
		            	
                tblModel.addRow(tbData);
            }
            JOptionPane.showMessageDialog(null, "Berhasil mengambil data!");
		    
	} catch (Exception es) {
	System.out.println(es);
	}
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("MM");
        int bulan = get_month.getMonth();
        int tahun = get_year.getYear();
        String querry_data = String.format("SELECT dataharian.dataharian_id, user.nama_depan, user.nama_belakang, user.email, dataharian.input_at FROM user INNER JOIN dataharian ON user.user_id = dataharian.user_id WHERE input_at BETWEEN '%d-%d-01' AND '%d-%d-01' ORDER BY dataharian.input_at ASC", tahun, bulan+1, tahun, bulan+2);

        
        try {
//            String querry_data = String.format("SELECT user.user_id, user.nama_depan, user.nama_belakang, alatverified.scan_id, alatverified.masker, alatverified.login_at FROM user INNER JOIN alatverified ON user.user_id = alatverified.user_id WHERE masker = 0 and login_at > '%s' and login_at < '%s 23:59:59' ", tanggal, tanggal);
            Connection conn = database.getConnect();
            PreparedStatement get_data = conn.prepareStatement(querry_data);
            ResultSet hasil = get_data.executeQuery();

            while(hasil.next()){
                String dataharian_id = String.valueOf(hasil.getInt("dataharian_id"));
                String namadepan = hasil.getString("nama_depan");
                String namabelakang = hasil.getString("nama_belakang");
                String email = hasil.getString("email");
                String input_at = hasil.getString("input_at");
                
                String tbData[] = {dataharian_id, namadepan, namabelakang, email, input_at};
                DefaultTableModel tblModel = (DefaultTableModel)tabel_databydate.getModel();
		            	
                tblModel.addRow(tbData);
            }
            JOptionPane.showMessageDialog(null, "Berhasil mengambil data!");


        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)tabel_databydate.getModel();
        while(tblModel.getRowCount() > 0){
            tblModel.removeRow(0);
        }
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        try {
            String querry_data = "SELECT dataharian.dataharian_id, user.nama_depan, user.nama_belakang, user.email, dataharian.input_at FROM user INNER JOIN dataharian ON user.user_id = dataharian.user_id ";
            Connection conn = database.getConnect();
            PreparedStatement get_data = conn.prepareStatement(querry_data);
            ResultSet hasil = get_data.executeQuery();

            while(hasil.next()){
                String dataharian_id = String.valueOf(hasil.getInt("dataharian_id"));
                String namadepan = hasil.getString("nama_depan");
                String namabelakang = hasil.getString("nama_belakang");
                String email = hasil.getString("email");
                String input_at = hasil.getString("input_at");
//		
                
                String tbData[] = {dataharian_id, namadepan, namabelakang, email, input_at};
                DefaultTableModel tblModel = (DefaultTableModel)tabel_getalldata.getModel();
		            	
                tblModel.addRow(tbData);
            }
            JOptionPane.showMessageDialog(null, "Berhasil mengambil data!");


        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)tabel_getalldata.getModel();
        while(tblModel.getRowCount() > 0){
            tblModel.removeRow(0);
        }
        JOptionPane.showMessageDialog(null, "Berhasil hapus tabel!");

    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)tabel_getAllDataByDate.getModel();
        while(tblModel.getRowCount() > 0){
            tblModel.removeRow(0);
        }
        JOptionPane.showMessageDialog(null, "Berhasil hapus tabel!");
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel24homepage(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24homepage
        // TODO add your handling code here:
        TabbedPane_Dashboard.setSelectedIndex(0);
    }//GEN-LAST:event_jLabel24homepage

    private void panel_bydate3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_bydate3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_bydate3MouseClicked

    private void jLabel26homepage(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26homepage
        // TODO add your handling code here:
        TabbedPane_Dashboard.setSelectedIndex(1);
    }//GEN-LAST:event_jLabel26homepage

    private void panel_bydate4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_bydate4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_bydate4MouseClicked

    private void jLabel28homepage(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28homepage
        // TODO add your handling code here:
        TabbedPane_Dashboard.setSelectedIndex(2);
    }//GEN-LAST:event_jLabel28homepage

    private void panel_bydate5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_bydate5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_bydate5MouseClicked

    private void jLabel30homepage(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30homepage
        // TODO add your handling code here:
        TabbedPane_Dashboard.setSelectedIndex(3);
    }//GEN-LAST:event_jLabel30homepage

    private void panel_bydate6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_bydate6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_bydate6MouseClicked

    private void jLabel32homepage(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32homepage
        // TODO add your handling code here:
        TabbedPane_Dashboard.setSelectedIndex(4);
    }//GEN-LAST:event_jLabel32homepage

    private void panel_bydate7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_bydate7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_bydate7MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = sdf.format(datechooser_jumlahpeople.getDate());
        String querry_data = String.format("SELECT COUNT(dataharian.dataharian_id) as 'Jumlah' FROM user INNER JOIN dataharian ON user.user_id = dataharian.user_id WHERE input_at = '%s'", tanggal);
        try {
            Connection conn = database.getConnect();
            PreparedStatement get_data = conn.prepareStatement(querry_data);
            ResultSet hasil = get_data.executeQuery();

            while(hasil.next()){
                String dataharian_id = String.valueOf(hasil.getInt("Jumlah"));
                jumlah.setText(dataharian_id);
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        // TODO add your handling code here:
        jumlah.setText("");
    }//GEN-LAST:event_jLabel33MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("MM");
        int bulan = get_jumlahmonth.getMonth();
        int tahun = get_jumlahyear.getYear();
        String querry_data = String.format("SELECT COUNT(dataharian.dataharian_id) as 'Jumlah' FROM user INNER JOIN dataharian ON user.user_id = dataharian.user_id WHERE input_at BETWEEN '%d-%d-01' AND '%d-%d-01' ORDER BY dataharian.input_at ASC", tahun, bulan+1, tahun, bulan+2);

        
        try {
//            String querry_data = String.format("SELECT user.user_id, user.nama_depan, user.nama_belakang, alatverified.scan_id, alatverified.masker, alatverified.login_at FROM user INNER JOIN alatverified ON user.user_id = alatverified.user_id WHERE masker = 0 and login_at > '%s' and login_at < '%s 23:59:59' ", tanggal, tanggal);
            Connection conn = database.getConnect();
            PreparedStatement get_data = conn.prepareStatement(querry_data);
            ResultSet hasil = get_data.executeQuery();

            while(hasil.next()){
                String dataharian_id = String.valueOf(hasil.getInt("Jumlah"));
                jumlah1.setText(dataharian_id);
            }


        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jLabel34MouseClicked

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel36MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataScientist_Dashboard_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataScientist_Dashboard_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataScientist_Dashboard_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataScientist_Dashboard_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataScientist_Dashboard_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabbedPane_Dashboard;
    private com.toedter.calendar.JDateChooser datechooser_getpeople;
    private com.toedter.calendar.JDateChooser datechooser_jumlahpeople;
    private com.toedter.calendar.JMonthChooser get_jumlahmonth;
    private com.toedter.calendar.JYearChooser get_jumlahyear;
    private com.toedter.calendar.JMonthChooser get_month;
    private com.toedter.calendar.JYearChooser get_year;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jumlah;
    private javax.swing.JLabel jumlah1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel10;
    private keeptoo.KGradientPanel kGradientPanel11;
    private keeptoo.KGradientPanel kGradientPanel12;
    private keeptoo.KGradientPanel kGradientPanel13;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private keeptoo.KGradientPanel kGradientPanel5;
    private keeptoo.KGradientPanel kGradientPanel6;
    private keeptoo.KGradientPanel kGradientPanel7;
    private keeptoo.KGradientPanel kGradientPanel8;
    private keeptoo.KGradientPanel kGradientPanel9;
    private javax.swing.JPanel panel_bydate3;
    private javax.swing.JPanel panel_bydate4;
    private javax.swing.JPanel panel_bydate5;
    private javax.swing.JPanel panel_bydate6;
    private javax.swing.JPanel panel_bydate7;
    private javax.swing.JPanel panel_getAllPeople;
    private javax.swing.JPanel panel_getdatapeoplebydate;
    private javax.swing.JPanel panel_getdatapeoplebymonth;
    private javax.swing.JPanel panel_getjumlahvisitorbydate;
    private javax.swing.JPanel panel_getjumlahvisitorbymonth;
    private javax.swing.JPanel panel_logout;
    private javax.swing.JScrollPane tabel_data2;
    private javax.swing.JTable tabel_databydate;
    private javax.swing.JTable tabel_getAllDataByDate;
    private javax.swing.JTable tabel_getalldata;
    // End of variables declaration//GEN-END:variables
}
