/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.text.SimpleDateFormat;
import tubespbo_autogatesystem.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author maula
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttongroup = new javax.swing.ButtonGroup();
        label_akuntidaktersedia = new javax.swing.JLabel();
        label_namadepan = new javax.swing.JLabel();
        field_namadepan = new javax.swing.JTextField();
        label_namabelakang = new javax.swing.JLabel();
        field_namabelakang = new javax.swing.JTextField();
        label_birthdate = new javax.swing.JLabel();
        field_birthdate = new com.toedter.calendar.JDateChooser();
        label_gender = new javax.swing.JLabel();
        rdbtn_laki = new javax.swing.JRadioButton();
        rdbtn_perempuan = new javax.swing.JRadioButton();
        label_nomortelepon = new javax.swing.JLabel();
        field_nomortelepon = new javax.swing.JTextField();
        label_email = new javax.swing.JLabel();
        field_email = new javax.swing.JTextField();
        label_username = new javax.swing.JLabel();
        field_username = new javax.swing.JTextField();
        label_password = new javax.swing.JLabel();
        field_password = new javax.swing.JPasswordField();
        label_repassword = new javax.swing.JLabel();
        field_repassword = new javax.swing.JPasswordField();
        button_register = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        label_back = new javax.swing.JLabel();
        label_passwordharussama = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setMinimumSize(new java.awt.Dimension(700, 530));
        setName("frame_login"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_akuntidaktersedia.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(label_akuntidaktersedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(706, 295, -1, -1));

        label_namadepan.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        label_namadepan.setText("Nama Depan");
        label_namadepan.setToolTipText("");
        getContentPane().add(label_namadepan, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 42, -1, -1));

        field_namadepan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_namadepanActionPerformed(evt);
            }
        });
        getContentPane().add(field_namadepan, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 61, 200, -1));

        label_namabelakang.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        label_namabelakang.setText("Nama Belakang");
        label_namabelakang.setToolTipText("");
        getContentPane().add(label_namabelakang, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 89, -1, -1));

        field_namabelakang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_namabelakangActionPerformed(evt);
            }
        });
        getContentPane().add(field_namabelakang, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 109, 200, -1));

        label_birthdate.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        label_birthdate.setText("Birth Date");
        label_birthdate.setToolTipText("");
        getContentPane().add(label_birthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 137, -1, -1));

        field_birthdate.setOpaque(false);
        getContentPane().add(field_birthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 157, 200, -1));

        label_gender.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        label_gender.setText("Gender");
        label_gender.setToolTipText("");
        getContentPane().add(label_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 187, -1, -1));

        buttongroup.add(rdbtn_laki);
        rdbtn_laki.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        rdbtn_laki.setText("M");
        getContentPane().add(rdbtn_laki, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 185, -1, -1));

        buttongroup.add(rdbtn_perempuan);
        rdbtn_perempuan.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        rdbtn_perempuan.setText("F");
        getContentPane().add(rdbtn_perempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 185, -1, -1));

        label_nomortelepon.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        label_nomortelepon.setText("Nomor Telepon");
        label_nomortelepon.setToolTipText("");
        getContentPane().add(label_nomortelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 211, -1, -1));

        field_nomortelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_nomorteleponActionPerformed(evt);
            }
        });
        getContentPane().add(field_nomortelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 231, 200, -1));

        label_email.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        label_email.setText("Email");
        label_email.setToolTipText("");
        getContentPane().add(label_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 259, -1, -1));

        field_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_emailActionPerformed(evt);
            }
        });
        getContentPane().add(field_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 279, 200, -1));

        label_username.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        label_username.setText("Username");
        label_username.setToolTipText("");
        getContentPane().add(label_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 307, -1, -1));

        field_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(field_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 327, 200, -1));

        label_password.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        label_password.setText("Password");
        label_password.setToolTipText("");
        getContentPane().add(label_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 361, -1, -1));
        getContentPane().add(field_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 381, 200, -1));

        label_repassword.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        label_repassword.setText("Re-Password");
        label_repassword.setToolTipText("");
        getContentPane().add(label_repassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 409, -1, -1));
        getContentPane().add(field_repassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 429, 200, -1));

        button_register.setBackground(new java.awt.Color(102, 102, 255));
        button_register.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button_register.setForeground(new java.awt.Color(255, 255, 255));
        button_register.setText("REGISTER");
        button_register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_registerMouseClicked(evt);
            }
        });
        button_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_registerActionPerformed(evt);
            }
        });
        getContentPane().add(button_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 463, 200, 33));

        jLabel4.setText("X");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keluar(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 0, 11, -1));

        kGradientPanel2.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 255, 255));

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 255, 204));
        kGradientPanel1.setkTransparentControls(false);

        label_back.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label_back.setForeground(new java.awt.Color(255, 255, 255));
        label_back.setText("<");
        label_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_to_login(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_back)
                .addContainerGap(269, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(label_back)
                .addGap(0, 514, Short.MAX_VALUE))
        );

        label_passwordharussama.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_passwordharussama.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)
                .addComponent(label_passwordharussama)
                .addGap(137, 137, 137))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_passwordharussama)
                .addGap(114, 114, 114))
        );

        getContentPane().add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void keluar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluar
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_keluar

    private void field_namadepanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_namadepanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_namadepanActionPerformed

    private void field_namabelakangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_namabelakangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_namabelakangActionPerformed

    private void field_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_emailActionPerformed

    private void field_nomorteleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_nomorteleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_nomorteleponActionPerformed

    private void field_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_usernameActionPerformed

    private void back_to_login(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_to_login
        // TODO add your handling code here:
        Login loginpage = new Login();
        loginpage.show();
        
        dispose();
    }//GEN-LAST:event_back_to_login

    private void button_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_registerMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_button_registerMouseClicked

    private void button_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_registerActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String namadepan;
        String namabelakang;
        String birthdate;
        Boolean gender;
        String nomortelepon;
        String email;
        String username;
        String password;
        
        if (field_password.getText().equals(field_repassword.getText())){
            namadepan = field_namadepan.getText();
            namabelakang = field_namabelakang.getText();
            birthdate = sdf.format(field_birthdate.getDate()); 
            if(rdbtn_laki.isSelected()) {
		gender = true;
            } else {
		gender = false;
            }
            nomortelepon = field_nomortelepon.getText();
            email = field_email.getText();
            username = field_username.getText();
            password = field_password.getText();
            
            User newUser = new User(namadepan, namabelakang, birthdate, gender, nomortelepon, email, username, password);
            newUser.input_biodata();
            
            Login loginpage = new Login();
            loginpage.show();
            
            dispose();
        } else {
            label_passwordharussama.setText("password harus sama!");
        }
    }//GEN-LAST:event_button_registerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_register;
    private javax.swing.ButtonGroup buttongroup;
    private com.toedter.calendar.JDateChooser field_birthdate;
    private javax.swing.JTextField field_email;
    private javax.swing.JTextField field_namabelakang;
    private javax.swing.JTextField field_namadepan;
    private javax.swing.JTextField field_nomortelepon;
    private javax.swing.JPasswordField field_password;
    private javax.swing.JPasswordField field_repassword;
    private javax.swing.JTextField field_username;
    private javax.swing.JLabel jLabel4;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel label_akuntidaktersedia;
    private javax.swing.JLabel label_back;
    private javax.swing.JLabel label_birthdate;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_gender;
    private javax.swing.JLabel label_namabelakang;
    private javax.swing.JLabel label_namadepan;
    private javax.swing.JLabel label_nomortelepon;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_passwordharussama;
    private javax.swing.JLabel label_repassword;
    private javax.swing.JLabel label_username;
    private javax.swing.JRadioButton rdbtn_laki;
    private javax.swing.JRadioButton rdbtn_perempuan;
    // End of variables declaration//GEN-END:variables
}
